main/urls.py
from django.urls import path

from .views import BBLoginView, BBLogoutView, ChangeUserInfoView, BBPasswordChangeView, DeleteUserView, \
    index, other_page, profile, RegisterDoneView, RegisterUserView, user_activate


app_name = 'main'
urlpatterns = [
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

my_django_bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    # статические файлы не кэшируюся веб-браузером
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    """Рассширенная модель юзера"""
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .apps import user_registered
from .models import AdvUser


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите пароль для проверки')

    def clean_password1(self):
        """Валидация пароля, введенного в первое поле"""
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 =self.cleaned_data['password1']
        password2 =self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        # отправка сигнала, чтобы отослать пользователю письмо с требованием активации
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.shortcuts import get_object_or_404, render
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .models import AdvUser
from .forms import ChangeUserInfoForm, RegisterUserForm
from .utilities import signer


class BBLoginView(LoginView):
    template_name = 'main/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя успешно изменен!'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """Контроллер странницы основных данных, который выполняет правку записи модели AdvUser"""
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        """Получение  ключа текущего пользователя( выполняется в начале исполнения контроллера-класса)"""
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """Извлечение исправляемой записи по полученному ключу"""
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален!')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterUserView(CreateView):
    """Контроллер, регистрирующий пользователя"""
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    """Контроллер, который выводит сообщение об успешной регистрации"""
    template_name = 'main/register_done.html'


def index(request):
    """Тестовая стартовая страница"""
    return render(request, 'main/index.html')


def other_page(request, page):
    """Страница со сведениями о сайте"""
    try:
        # пытаемся загрузить полный путь к нужному шаблону
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


@login_required
def profile(request):
    return render(request, 'main/profile.html')


def user_activate(request, sign):
    """Активация нового пользователя"""
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            {% block title %}Главная{% endblock %} - Доска объявлений
        </title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Объявления</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
                    {% if user.is_authenticated %}
                         <li class="nav-item dropdown">
                             <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                                href="#" role="button" aria-haspopup="true"
                                aria-expanded="false">Профиль</a>
                             <div class="dropdown-menu">
                                 <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                                 <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить личные данные</a>
                                 <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>
                                 <div class="dropdown-divider"></div>
                                 <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                                 <div class="dropdown-divider"></div>
                                 <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
                             </div>
                         </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                        </li>
                    {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root" href="{% url 'main:index' %}">Главная</a>
                <span class="nav-link root font-weight-bold">Недвижемость</span>
                <a class="nav-link" href="#">Жилье</a>
                <a class="nav-link" href="#">Склады</a>
                <a class="nav-link" href="#">Гаражи</a>
                <span class="nav-link root font-weight-bold" href="#">Транспорт</span>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}"> О сайте</a>
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; ysv</p>
        </footer>
    </body>
</html>

main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block content %}
    <h2>О сайте</h2>
    <p>Сайт для публикации объявлений о продаже, разбитых на рубрики</p>
{% endblock %}

main/templates/main/activation_done.html
{% extends 'layout/basic.html' %}

{% block title %}Активация выполнена{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Пользователь с таким именем успешно активирован.</p>
    <p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

main/templates/main/bad_signature.html
{% extends 'layout/basic.html' %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Активация пользователя с таким именем прошла неудачно.</p>
    <p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load  bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
    <h2>Правка личных данных пользователя {{ user.username }}</h2>
    <form methd="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сохранить' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/delete_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
    <h2>Удаление пользователя {{ object.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% buttons submit='Удалить' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
    <h2>Последние 10 объявлений</h2>
{% endblock %}

main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <input type="hidden" name="text" value="{{ next }}">
            {% buttons submit='Войти' %}{% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
    <h2>Выход</h2>
    <p>Вы успешно разлогинились!</p>
{% endblock %}

main/templates/main/password_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Изменение пароля{% endblock %}

{% block content %}
    <h2>Смена пароля пользователя {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сменить пароль' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
        <p>Здравствуйте!</p>
    {% endif %}
    <h3>Ваши объявления:</h3>
{% endblock %}

main/templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <p>Регистрация нового пользователя завершена!</p>
    <p>Для активации пользователя на указанный адрес электронной почты выслано письмо</p>
{% endblock %}

main/templates/main/register_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/user_is_activated.html
{% extends 'layout/basic.html' %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Пользователь с таким именем был активирован ранее.</p>
    <p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}